sudo: false # use container-based build
language: fortran
notifications:
    email: false

compiler: gfortran-6
os: linux
dist: xenial
sudo: required
env: TESTID='summa_linux'
addons:
  apt:
    packages:
      - gcc-6
      - libnetcdff-dev
      - liblapack-dev
   
install:
   - summa_install
script:
  - summa_script
after_success:
  - summa_after_success
after_failure:
  - summa_after_failure
